version: '3'
services:
  telegram_bot:
    build:
      context: ./
      dockerfile: dockerfile
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword